<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Iteration | An R Primer for Social Scientists</title>
  <meta name="description" content="7 Iteration | An R Primer for Social Scientists" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Iteration | An R Primer for Social Scientists" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Iteration | An R Primer for Social Scientists" />
  
  
  

<meta name="author" content="Aditya Ranganath" />


<meta name="date" content="2024-02-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="writing-functions.html"/>
<link rel="next" href="data-transfer-part-1-importing-data-into-r-studio.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.31/datatables.js"></script>
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="libs/dt-ext-scroller-1.13.6/css/scroller.dataTables.min.css" rel="stylesheet" />
<script src="libs/dt-ext-scroller-1.13.6/js/dataTables.scroller.min.js"></script>
<link href="libs/dt-ext-fixedcolumns-1.13.6/css/fixedColumns.dataTables.min.css" rel="stylesheet" />
<script src="libs/dt-ext-fixedcolumns-1.13.6/js/dataTables.fixedColumns.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R Primer</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="2.1" data-path="preliminaries.html"><a href="preliminaries.html#r-and-rstudio-installation"><i class="fa fa-check"></i><b>2.1</b> R and RStudio Installation</a></li>
<li class="chapter" data-level="2.2" data-path="preliminaries.html"><a href="preliminaries.html#the-rstudio-interface"><i class="fa fa-check"></i><b>2.2</b> The RStudio Interface</a></li>
<li class="chapter" data-level="2.3" data-path="preliminaries.html"><a href="preliminaries.html#install-packages"><i class="fa fa-check"></i><b>2.3</b> Install Packages</a></li>
<li class="chapter" data-level="2.4" data-path="preliminaries.html"><a href="preliminaries.html#load-libraries"><i class="fa fa-check"></i><b>2.4</b> Load libraries</a></li>
</ul></li>
<li class="part"><span><b>I Foundations</b></span></li>
<li class="chapter" data-level="3" data-path="r-as-a-calculator.html"><a href="r-as-a-calculator.html"><i class="fa fa-check"></i><b>3</b> R as a Calculator</a></li>
<li class="chapter" data-level="4" data-path="object-assignment-and-manipulation.html"><a href="object-assignment-and-manipulation.html"><i class="fa fa-check"></i><b>4</b> Object assignment and manipulation</a></li>
<li class="chapter" data-level="5" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>5</b> Data Structures</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>5.1</b> Vectors</a></li>
<li class="chapter" data-level="5.2" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>5.2</b> Data Frames</a></li>
<li class="chapter" data-level="5.3" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>5.3</b> Lists</a></li>
<li class="chapter" data-level="5.4" data-path="data-structures.html"><a href="data-structures.html#identifying-data-structures"><i class="fa fa-check"></i><b>5.4</b> Identifying Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="writing-functions.html"><a href="writing-functions.html"><i class="fa fa-check"></i><b>6</b> Writing Functions</a></li>
<li class="chapter" data-level="7" data-path="iteration.html"><a href="iteration.html"><i class="fa fa-check"></i><b>7</b> Iteration</a></li>
<li class="part"><span><b>II Applied Data Research in R</b></span></li>
<li class="chapter" data-level="8" data-path="data-transfer-part-1-importing-data-into-r-studio.html"><a href="data-transfer-part-1-importing-data-into-r-studio.html"><i class="fa fa-check"></i><b>8</b> Data Transfer Part 1: Importing Data into R Studio</a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-transfer-part-1-importing-data-into-r-studio.html"><a href="data-transfer-part-1-importing-data-into-r-studio.html#reading-in-a-dataset-from-a-directory-on-your-computer"><i class="fa fa-check"></i><b>8.1</b> Reading in a dataset from a directory on your computer</a></li>
<li class="chapter" data-level="8.2" data-path="data-transfer-part-1-importing-data-into-r-studio.html"><a href="data-transfer-part-1-importing-data-into-r-studio.html#reading-in-multiple-datasets-from-your-disk"><i class="fa fa-check"></i><b>8.2</b> Reading in multiple datasets from your disk</a></li>
<li class="chapter" data-level="8.3" data-path="data-transfer-part-1-importing-data-into-r-studio.html"><a href="data-transfer-part-1-importing-data-into-r-studio.html#reading-in-a-dataset-from-cloud-storage"><i class="fa fa-check"></i><b>8.3</b> Reading in a dataset from cloud storage</a></li>
<li class="chapter" data-level="8.4" data-path="data-transfer-part-1-importing-data-into-r-studio.html"><a href="data-transfer-part-1-importing-data-into-r-studio.html#reading-in-data-from-an-r-package"><i class="fa fa-check"></i><b>8.4</b> Reading in data from an R package</a></li>
<li class="chapter" data-level="8.5" data-path="data-transfer-part-1-importing-data-into-r-studio.html"><a href="data-transfer-part-1-importing-data-into-r-studio.html#reading-in-data-from-a-website"><i class="fa fa-check"></i><b>8.5</b> Reading in data from a website</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html"><i class="fa fa-check"></i><b>9</b> Numeric Data Summarizing, Processing and Wrangling Tasks</a>
<ul>
<li class="chapter" data-level="9.1" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#summary-statistics"><i class="fa fa-check"></i><b>9.1</b> Summary Statistics</a></li>
<li class="chapter" data-level="9.2" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#basic-data-cleaning-and-preparation-tasks"><i class="fa fa-check"></i><b>9.2</b> Basic Data Cleaning and Preparation Tasks</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#rearranging-columns"><i class="fa fa-check"></i><b>9.2.1</b> Rearranging Columns</a></li>
<li class="chapter" data-level="9.2.2" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#renaming-variables"><i class="fa fa-check"></i><b>9.2.2</b> Renaming Variables</a></li>
<li class="chapter" data-level="9.2.3" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#sorting-a-dataset-in-ascending-or-descending-order-with-respect-to-a-variable"><i class="fa fa-check"></i><b>9.2.3</b> Sorting a dataset in ascending or descending order with respect to a variable</a></li>
<li class="chapter" data-level="9.2.4" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#creating-new-variables-based-on-existing-variables"><i class="fa fa-check"></i><b>9.2.4</b> Creating new variables based on existing variables</a></li>
<li class="chapter" data-level="9.2.5" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#selecting-or-deleting-variables"><i class="fa fa-check"></i><b>9.2.5</b> Selecting or Deleting Variables</a></li>
<li class="chapter" data-level="9.2.6" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#recoding-variables"><i class="fa fa-check"></i><b>9.2.6</b> Recoding Variables</a></li>
<li class="chapter" data-level="9.2.7" data-path="numeric-data-summarizing-processing-and-wrangling-tasks.html"><a href="numeric-data-summarizing-processing-and-wrangling-tasks.html#subsetting-variables"><i class="fa fa-check"></i><b>9.2.7</b> Subsetting Variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="exploratory-visualization.html"><a href="exploratory-visualization.html"><i class="fa fa-check"></i><b>10</b> Exploratory Visualization</a>
<ul>
<li class="chapter" data-level="10.1" data-path="exploratory-visualization.html"><a href="exploratory-visualization.html#bar-charts"><i class="fa fa-check"></i><b>10.1</b> Bar Charts</a></li>
<li class="chapter" data-level="10.2" data-path="exploratory-visualization.html"><a href="exploratory-visualization.html#scatterplots"><i class="fa fa-check"></i><b>10.2</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html"><i class="fa fa-check"></i><b>11</b> Elementary Data Analysis</a>
<ul>
<li class="chapter" data-level="11.1" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#computing-correlations"><i class="fa fa-check"></i><b>11.1</b> Computing correlations</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#computing-correlations-between-two-variables-in-a-dataset"><i class="fa fa-check"></i><b>11.1.1</b> Computing correlations between two variables in a dataset</a></li>
<li class="chapter" data-level="11.1.2" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#generating-and-exporting-a-correlation-matrix"><i class="fa fa-check"></i><b>11.1.2</b> Generating and exporting a correlation matrix</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#basic-regression-analysis"><i class="fa fa-check"></i><b>11.2</b> Basic regression analysis</a></li>
<li class="chapter" data-level="11.3" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#working-with-categorical-variables-in-a-regression-model"><i class="fa fa-check"></i><b>11.3</b> Working with categorical variables in a regression model</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#working-with-categorical-variables-using-factors"><i class="fa fa-check"></i><b>11.3.1</b> Working with categorical variables using factors</a></li>
<li class="chapter" data-level="11.3.2" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#working-with-categorical-variables-by-creating-dummy-variables"><i class="fa fa-check"></i><b>11.3.2</b> Working with categorical variables by creating dummy variables</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#working-with-interaction-terms-in-regression-models"><i class="fa fa-check"></i><b>11.4</b> Working with interaction terms in regression models</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#plotting-marginal-effects"><i class="fa fa-check"></i><b>11.4.1</b> Plotting marginal effects</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="elementary-data-analysis.html"><a href="elementary-data-analysis.html#creating-and-exporting-regression-tables"><i class="fa fa-check"></i><b>11.5</b> Creating and exporting regression tables</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An R Primer for Social Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="iteration" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> Iteration<a href="iteration.html#iteration" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Once we have a function written down, it is straightforward to apply that function to multiple inputs in an iterative fashion. For example, let’s say you have four different Fahrenheit temperature values that you would like to convert to celsius, using the <code>fahrenheit_to_celsius_converter</code> we developed above. One option would be to apply the <code>fahrenheit_to_celsius_converter</code> function to each of the Fahrenheit temperature inputs individually. For example, let’s say our Fahrenheit values, which we’d like to convert to celsius, are the following: 45.6, 95.9, 67.8, 43. We could, of course, run these values through the function individually, as below:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="iteration.html#cb89-1" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_converter</span>(<span class="at">fahrenheit_input=</span><span class="fl">45.6</span>)</span></code></pre></div>
<pre><code>## [1] 7.555556</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="iteration.html#cb91-1" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_converter</span>(<span class="at">fahrenheit_input=</span><span class="fl">95.9</span>)</span></code></pre></div>
<pre><code>## [1] 35.5</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="iteration.html#cb93-1" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_converter</span>(<span class="at">fahrenheit_input=</span><span class="fl">67.8</span>)</span></code></pre></div>
<pre><code>## [1] 19.88889</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="iteration.html#cb95-1" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_converter</span>(<span class="at">fahrenheit_input=</span><span class="fl">43.</span>)</span></code></pre></div>
<pre><code>## [1] 6.111111</code></pre>
<p>This is manageable with a collection of only four Fahrenheit values, but would quickly become tedious if you had a substantially larger set of Fahrenheit temperature values that required conversion. Instead of manually applying the function to each individual input value, we can instead put these values into a vector, and then iteratively apply the <code>fahrenheit_to_celsius_converter</code> function to each of these vector elements.</p>
<p>Let’s first assign our Fahrenheit temperature values to a numeric vector object named <code>fahrenheit_input_vector</code>:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="iteration.html#cb97-1" tabindex="-1"></a><span class="co"># makes a vector out of Fahrenheit values we want to convert, and assigns it to a new object named &quot;fahrenheit_input_vector&quot;</span></span>
<span id="cb97-2"><a href="iteration.html#cb97-2" tabindex="-1"></a>fahrenheit_input_vector<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fl">45.6</span>, <span class="fl">95.9</span>, <span class="fl">67.8</span>, <span class="dv">43</span>)</span></code></pre></div>
<p>Our goal is to also iteratively apply our function to all of these vector elements, and deposit the transformed results into a new vector. In programming languages, functions are typically applied to to multiple inputs in an iterative fashion using a construct known as a for-loop, which some of you may already be familiar with. R users also frequently use specialized functions (instead of for-loops) to iterate over elements; this is often faster, or at the very least, makes R scripts more readable. One family of these iterative functions is the “Apply” family of functions. A more recent set of functions that facilitate iteration is part of the <em>tidyverse</em>, and is found within the <a href="https://purrr.tidyverse.org/"><em>purrr</em></a> package. These functions are known as <code>map()</code> functions, and we will use them here to iteratively apply our functions to multiple inputs.</p>
<p>Let’s see how we can use a <code>map()</code> function to sequentially apply the <code>fahrenheit_to_celsius_converter()</code> function we created to several different values for the “fahrenheit_input” argument, contained in <code>fahrenheit_input_vector</code>. We’ll pass <code>fahrenheit_input_vector</code> as the first argument to the <code>map_dbl()</code> function, and <code>fahrenheit_to_celsius_converter</code> (i.e. the function we want to apply iteratively to the elements in `the<code>fahrenheit_input_vector</code> ) as the second argument. The result of this operation will be a new “results vector”, containing the transformed temperature values for each input in the original vector of Fahrenheit values (<code>fahrenheit_input_vector</code>). We’ll assign this result/output vector to a new object named <code>celsius_outputs_vector</code>:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="iteration.html#cb98-1" tabindex="-1"></a><span class="co"># Iteratively applies the &quot;fahrenheit_to_celsius_converter&quot; to celsius input values in &quot;fahrenheit_input_vector&quot; and assigns the resulting vector of converted temperature values to &quot;celsius_ouputs_vector&quot;</span></span>
<span id="cb98-2"><a href="iteration.html#cb98-2" tabindex="-1"></a>celsius_outputs_vector<span class="ot">&lt;-</span><span class="fu">map_dbl</span>(fahrenheit_input_vector, fahrenheit_to_celsius_converter)</span></code></pre></div>
<p>In short, the code above takes ``fahrenheit_input_vector<code>(i.e. a vector with the numbers 45.6, 95.9, 67.8, 43), and runs each of these numbers through the</code>fahrenheit_converter()<code>function, and sequentially deposits the transformed result to the newly created</code>celsius_outputs_vector()``` object, which contains the following elements:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="iteration.html#cb99-1" tabindex="-1"></a><span class="co"># prints contents of &quot;celsius_outputs_vector&quot;</span></span>
<span id="cb99-2"><a href="iteration.html#cb99-2" tabindex="-1"></a>celsius_outputs_vector</span></code></pre></div>
<pre><code>## [1]  7.555556 35.500000 19.888889  6.111111</code></pre>
<p>More explicitly, the code that reads <code>celsius_outputs_vector&lt;-map_dbl(fahrenheit_input_vector, fahrenheit_converter)</code> did the following:</p>
<ol style="list-style-type: decimal">
<li>Pass 45.6 (the first element in the input vector, <code>fahrenheit_input_vector</code>) to the <code>fahrenheit_converter()</code> function, and place the output (7.555556) as the first element in a new vector of transformed values, named <code>celsius_outputs_vector</code>.</li>
<li>Pass 95.9 (the second element in the input vector, <code>fahrenheit_input_vector</code>) to the <code>fahrenheit_converter()</code> function, and deposit the output (35.500000) as the second element in <code>celsius_outputs_vector</code>.</li>
<li>Pass 67.8 (the third element in the input vector, <code>fahrenheit_input_vector</code>) to the <code>fahrenheit_converter()</code> function, and deposit the output (19.888889) as the third element in <code>celsius_outputs_vector</code>.</li>
<li>Pass 43 (the fourth element in the input vector, <code>fahrenheit_input_vector</code>) to the <code>fahrenheit_converter()</code> function, and deposit the output (6.111111) as the fourth element in <code>celsius_outputs_vector</code>.</li>
</ol>
<p>There are a variety of <code>map()</code> functions from the <em>purrr</em> package, and the precise one you should use turns on the number of arguments used by the function (in this example, there is of course only one argument, i.e. “fahrenheit_input”), and the desired class of the output (i.e. numeric vector, character vector, data frame, list etc.). For example, let’s say we want to apply the <code>fahrenheit_to_celsius_converter</code> function iteratively to the input values in <code>fahrenheit_input_vector</code>, but that we want the output values to be stored as a list, rather than as a vector. Instead of using the <code>map_dbl()</code> function, we can use the <code>map()</code> function, which always returns outputs as a list. Below, we pass our input vector (<code>fahrenheit_input_vector</code>), and the function we want to iteratively apply to the elements of the input vector (<code>fahrenheit_converter</code>) to the <code>map()</code> function. We’ll assign the output list to a new object named <code>celsius_outputs_list</code>:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="iteration.html#cb101-1" tabindex="-1"></a><span class="co"># iteratively applies the &quot;fahrenheit_to_celsius_converter&quot; function to the input values in &quot;fahrenheit_input_vector&quot;, and assigns the list of celsius output values to a new object named &quot;celsius_outputs_list&quot;</span></span>
<span id="cb101-2"><a href="iteration.html#cb101-2" tabindex="-1"></a>celsius_outputs_list<span class="ot">&lt;-</span><span class="fu">map</span>(fahrenheit_input_vector, fahrenheit_to_celsius_converter)</span></code></pre></div>
<p>Let’s print out the list of output values:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="iteration.html#cb102-1" tabindex="-1"></a><span class="co"># prints contents of &quot;celsius_outputs_list&quot;</span></span>
<span id="cb102-2"><a href="iteration.html#cb102-2" tabindex="-1"></a>celsius_outputs_list</span></code></pre></div>
<pre><code>## [[1]]
## [1] 7.555556
## 
## [[2]]
## [1] 35.5
## 
## [[3]]
## [1] 19.88889
## 
## [[4]]
## [1] 6.111111</code></pre>
<p>We can confirm that <code>celsius_outputs_list</code> is indeed a list using the <code>class()</code> function that we introduced earlier:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="iteration.html#cb104-1" tabindex="-1"></a><span class="co"># checks data structure of &quot;celsius_outputs_list&quot;</span></span>
<span id="cb104-2"><a href="iteration.html#cb104-2" tabindex="-1"></a><span class="fu">class</span>(celsius_outputs_list)</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<p>Now, let’s say we we want to organize our information in a data frame, where one column represents our Fahrenheit input values, and the other column represents the corresponding Celsius output values. To do so, we’ll first slightly modify our function to return a data frame:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="iteration.html#cb106-1" tabindex="-1"></a><span class="co"># Creates function that takes an input value in degrees Fahrenheit (fahrenheit_input), converts this value to Celsius, and returns a data frame with the input Fahrenheit temperature value as one column, and the corresponding Celsius temperature value as another column; the function is assigned to a new object named &quot;fahrenheit_to_celsius_converter_df&quot; </span></span>
<span id="cb106-2"><a href="iteration.html#cb106-2" tabindex="-1"></a>fahrenheit_to_celsius_converter_df<span class="ot">&lt;-</span><span class="cf">function</span>(fahrenheit_input){</span>
<span id="cb106-3"><a href="iteration.html#cb106-3" tabindex="-1"></a>  celsius_output<span class="ot">&lt;-</span>(fahrenheit_input<span class="dv">-32</span>)<span class="sc">*</span>(<span class="dv">5</span><span class="sc">/</span><span class="dv">9</span>)</span>
<span id="cb106-4"><a href="iteration.html#cb106-4" tabindex="-1"></a>  celsius_output_df<span class="ot">&lt;-</span><span class="fu">data.frame</span>(fahrenheit_input, celsius_output)</span>
<span id="cb106-5"><a href="iteration.html#cb106-5" tabindex="-1"></a>  <span class="fu">return</span>(celsius_output_df)</span>
<span id="cb106-6"><a href="iteration.html#cb106-6" tabindex="-1"></a>}</span></code></pre></div>
<p>Now, let’s test out this new function for a single “fahrenheit_input” value, to make sure it works as expected; we’ll test it out for a value of 63 degrees Fahrenheit:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="iteration.html#cb107-1" tabindex="-1"></a><span class="co"># applies &quot;fahrenheit_to_celsius_converter_df&quot; function to input value of 63 degrees Fahrenheit</span></span>
<span id="cb107-2"><a href="iteration.html#cb107-2" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_converter_df</span>(<span class="at">fahrenheit_input=</span><span class="dv">63</span>)</span></code></pre></div>
<pre><code>##   fahrenheit_input celsius_output
## 1               63       17.22222</code></pre>
<p>Having confirmed that the function works as expected, let’s now assemble a dataset using multiple Fahrenheit input values, where one column consists of these input values, and the second column consists of the corresponding Celsius outputs. We can do so using the <code>map_dfr()</code> function from the <em>purrr</em> package, which is a cousin of the <code>map()</code> and <code>map_dbl()</code> functions we explored above. While the <code>map()</code> function returns function outputs in a list, and the <code>map_dbl()</code> function returns function outputs in a numeric vector, the <code>map_dfr()</code> is used to bind together multiple function outputs rowwise into a data frame. To make this more concrete, let’s consider the code below, which uses <code>map_dfr()</code> to iteratively apply the <code>fahrenheit_to_celsius_converter_df</code> function to the Fahrenheit values in <code>fahrenheit_input_vector</code>, and assemble the resulting rows into a data frame that is assigned to a new object named <code>celsius_outputs_df</code>:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="iteration.html#cb109-1" tabindex="-1"></a><span class="co"># Iteratively applies the &quot;fahrenheit_to_celsius_converter_df&quot; function to input values in &quot;fahrenheit_input_vector&quot; to generate a data frame with column of input Fahrenheit values, and column of corresponding output Celsius values; assigns this data frame to a new object named &quot;celsius_outputs_df&quot;</span></span>
<span id="cb109-2"><a href="iteration.html#cb109-2" tabindex="-1"></a>celsius_outputs_df<span class="ot">&lt;-</span><span class="fu">map_dfr</span>(fahrenheit_input_vector, fahrenheit_to_celsius_converter_df)</span></code></pre></div>
<p>Let’s now print the contents of <code>celsius_outputs_df</code>:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="iteration.html#cb110-1" tabindex="-1"></a><span class="co"># prints contents of </span></span>
<span id="cb110-2"><a href="iteration.html#cb110-2" tabindex="-1"></a>celsius_outputs_df</span></code></pre></div>
<pre><code>##   fahrenheit_input celsius_output
## 1             45.6       7.555556
## 2             95.9      35.500000
## 3             67.8      19.888889
## 4             43.0       6.111111</code></pre>
<p>We now have a dataset with one column consisting of our Fahrenheit inputs (taken from <code>fahrenheit_input_vector</code>), and a second column consisting of our Celsius outputs (derived by applying the <code>fahrenheit_to_celsius_converter_df()</code> function to our vector of input values, `<code>fahrenheit_input_vector</code>).</p>
<p>We’ve just covered three different <em>purrr</em> functions: <code>map()</code> (which returns a list), <code>map_dbl()</code> (which returns a vector), and <code>map_dfr()</code> (which returns a dataframe). There are other map functions which return different types of objects; you can see a list of these other map functions by inspecting the documentation for the <code>map()</code> function:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="iteration.html#cb112-1" tabindex="-1"></a>?map</span></code></pre></div>
<p>The process of iteratively applying a function with more than one argument is beyond the scope of the workshop, but the same general principles are at work in those cases. If you’d like to explore the process of iteratively applying a function with two arguments, or more than two arguments, check out the documentation for the <code>map2()</code> and <code>pmap()</code> functions, respectively.</p>
<p>Before we move into the next section, let’s consider one more example of how you can use your own custom-written functions in conjunction with the iteration functions in the <em>purrr</em> package to write scripts that can help you to automate tedious tasks. In particular, we’ll demonstrate the utility of the list data structure in helping you to carry out such automation tasks.</p>
<p>Let’s say, for example, that you have temperature values stored in Fahrenheit, for multiple countries, and want to quickly convert those country-level values to degrees Celsius. Suppose that these Fahrenheit values are stored in a series of vectors:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="iteration.html#cb113-1" tabindex="-1"></a><span class="co"># creates sample country-level Fahrenheit data for Country A</span></span>
<span id="cb113-2"><a href="iteration.html#cb113-2" tabindex="-1"></a>countryA_fahrenheit<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">55</span>,<span class="dv">67</span>,<span class="dv">91</span>,<span class="dv">23</span>, <span class="dv">77</span>, <span class="dv">98</span>, <span class="dv">27</span>)</span>
<span id="cb113-3"><a href="iteration.html#cb113-3" tabindex="-1"></a></span>
<span id="cb113-4"><a href="iteration.html#cb113-4" tabindex="-1"></a><span class="co"># creates sample country-level Fahrenheit data for Country B</span></span>
<span id="cb113-5"><a href="iteration.html#cb113-5" tabindex="-1"></a>countryB_fahrenheit<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">33</span>,<span class="dv">45</span>,<span class="dv">11</span>,<span class="dv">66</span>, <span class="dv">44</span>)</span>
<span id="cb113-6"><a href="iteration.html#cb113-6" tabindex="-1"></a></span>
<span id="cb113-7"><a href="iteration.html#cb113-7" tabindex="-1"></a><span class="co"># creates sample country-level Fahrenheit data for Country C</span></span>
<span id="cb113-8"><a href="iteration.html#cb113-8" tabindex="-1"></a>countryC_fahrenheit<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">60</span>,<span class="dv">55</span>,<span class="dv">12</span>,<span class="dv">109</span>)</span>
<span id="cb113-9"><a href="iteration.html#cb113-9" tabindex="-1"></a></span>
<span id="cb113-10"><a href="iteration.html#cb113-10" tabindex="-1"></a><span class="co"># creates sample country-level Fahrenheit data for Country D</span></span>
<span id="cb113-11"><a href="iteration.html#cb113-11" tabindex="-1"></a>countryD_fahrenheit<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">76</span>, <span class="dv">24</span>, <span class="dv">77</span>, <span class="dv">78</span>)</span></code></pre></div>
<p>Let’s say that we want to take all of these vectors, and iteratively pass them as arguments to the <code>fahrenheit_to_celsius_converter_df</code> function, thereby creating four country-specific data frames that have the original Fahrenheit values in one column and the transformed Celsius values in the other column. The easiest way to do this is to first put our input vectors into a list, which we’ll assign to a new object named <code>temperature_input_list</code>:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="iteration.html#cb114-1" tabindex="-1"></a><span class="co"># Creates list of input vectors and assigns this list to new object named &quot;input_list&quot;</span></span>
<span id="cb114-2"><a href="iteration.html#cb114-2" tabindex="-1"></a>temperature_input_list<span class="ot">&lt;-</span><span class="fu">list</span>(countryA_fahrenheit, countryB_fahrenheit, countryC_fahrenheit, countryD_fahrenheit) </span></code></pre></div>
<p>Now, we’ll use the <code>map()</code> function to iteratively pass the vectors in <code>temperature_input_list</code> as arguments to the <code>fahrenheit_to_celsius_converter_df</code> function, and deposits the resulting data frames into a list; we’ll assign this list that contains the output data frames to a new list object, named <code>processed_temperature_data_list</code>:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="iteration.html#cb115-1" tabindex="-1"></a><span class="co"># Iteratively passes vectors in &quot;temperature_input_list&quot; as arguments to &quot;fahrenheit_to_celsius_converter_df&quot; and deposits the resulting data frames to a list, which is assigned to a new object named &quot;processed_temperature_data_list&quot;</span></span>
<span id="cb115-2"><a href="iteration.html#cb115-2" tabindex="-1"></a>processed_temperature_data_list<span class="ot">&lt;-</span><span class="fu">map</span>(temperature_input_list, fahrenheit_to_celsius_converter_df)</span></code></pre></div>
<p>In effect, the code above takes the <code>countryA_fahrenheit</code> vector, uses it as the argument to the <code>fahrenheit_to_celsius_converter_df</code> function, and deposits the resulting data frame as the first element in the <code>processed_temperature_data_list</code> list; it then takes the <code>countryB_fahrenheit</code> vector, uses it as the argument to the <code>fahrenheit_to_celsius_converter_df</code> function, and deposits the resulting data frame as the second element in the <code>processed_temperature_data_list</code> list; and so on.</p>
<p>Let’s print the contents of <code>processed_temperature_data_list</code> and confirm that our data frames have been created as expected:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="iteration.html#cb116-1" tabindex="-1"></a><span class="co"># prints contents of &quot;processed_temperature_data_list&quot;</span></span>
<span id="cb116-2"><a href="iteration.html#cb116-2" tabindex="-1"></a>processed_temperature_data_list</span></code></pre></div>
<pre><code>## [[1]]
##   fahrenheit_input celsius_output
## 1               55      12.777778
## 2               67      19.444444
## 3               91      32.777778
## 4               23      -5.000000
## 5               77      25.000000
## 6               98      36.666667
## 7               27      -2.777778
## 
## [[2]]
##   fahrenheit_input celsius_output
## 1               33      0.5555556
## 2               45      7.2222222
## 3               11    -11.6666667
## 4               66     18.8888889
## 5               44      6.6666667
## 
## [[3]]
##   fahrenheit_input celsius_output
## 1               60       15.55556
## 2               55       12.77778
## 3               12      -11.11111
## 4              109       42.77778
## 
## [[4]]
##   fahrenheit_input celsius_output
## 1               76      24.444444
## 2               24      -4.444444
## 3               77      25.000000
## 4               78      25.555556</code></pre>
<p>As an exercise, try and extract a given dataset from <code>processed_temperature_data_list</code> using the indexing method we discussed above. Additionally, see if you can assign names to the list elements in <code>processed_temperature_data_list</code>.</p>

</div>



            </section>

          </div>
        </div>
      </div>
<a href="writing-functions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-transfer-part-1-importing-data-into-r-studio.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/aranganath24/IBS_CRDDS_Rworkshop/edit/main/03-foundations.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/aranganath24/IBS_CRDDS_Rworkshop/blob/main/03-foundations.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
